"""Configuration and shared constants for the Checkpoint Scout agent."""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

PROJECT_ROOT = Path(__file__).parent.parent
DATA_DIR = PROJECT_ROOT / "data"
OUTPUTS_DIR = PROJECT_ROOT / "outputs"
PROMPTS_DIR = PROJECT_ROOT / "prompts"

DATA_DIR.mkdir(exist_ok=True)
OUTPUTS_DIR.mkdir(exist_ok=True)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

# Repos to scan. Curated for: high star count, active AI-coding usage in PRs,
# maintainers who engage publicly. Mix of frameworks, infra, and dev tools.
TARGET_REPOS = [
    "vercel/next.js",
    "facebook/react",
    "microsoft/vscode",
    "nodejs/node",
    "python/cpython",
    "rust-lang/rust",
    "golang/go",
    "kubernetes/kubernetes",
    "pytorch/pytorch",
    "huggingface/transformers",
    "langchain-ai/langchain",
    "ggerganov/llama.cpp",
    "supabase/supabase",
    "denoland/deno",
    "astral-sh/ruff",
]

# Search queries that surface AI-coding pain on GitHub's issue search.
# Each query is a (query_string, pain_type_hint) tuple.
PAIN_SEARCH_QUERIES = [
    ('"AI-generated" review in:comments updated:>={recent_date}', "ai_authorship_concern"),
    ('"too large to review" in:comments updated:>={recent_date}', "oversized_pr"),
    ('"lost context" in:comments updated:>={recent_date}', "context_loss"),
    ('"what is this PR trying to do" in:comments updated:>={recent_date}', "intent_unclear"),
    ('"AI slop" in:comments updated:>={recent_date}', "ai_quality_complaint"),
    ('"generated by copilot" OR "generated by claude" OR "generated by cursor" in:comments updated:>={recent_date}', "ai_attribution"),
]

# Classification thresholds
MIN_PAIN_SCORE = 6  # out of 10
MAX_CANDIDATES_TO_CLASSIFY = 100
MAX_PAIN_MOMENTS_TO_GENERATE = 5  # we'll pick top 3 for the submission

# Model selection
CLASSIFICATION_MODEL = "claude-opus-4-7"
GENERATION_MODEL = "claude-opus-4-7"
