import { GitFork } from 'lucide-react';

export function Footer() {
  return (
    <footer className="border-t border-stone-200 py-8 px-4 text-center">
      <p className="text-sm text-stone-500">
        All artifacts are drafts. Nothing posted. Human-in-the-loop by design.
      </p>
      <div className="mt-3 flex items-center justify-center gap-4 text-xs text-stone-500">
        <a
          href="https://github.com/aunshx/watchtower"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1.5 hover:text-blue-600 transition-colors"
        >
          <GitFork size={13} />
          aunshx/watchtower
        </a>
        <span>·</span>
        <span>Generated by Watchtower</span>
      </div>
    </footer>
  );
}
